"""
MySQL Database Service for Product Builder
Handles persistent storage of projects, builds, and chat history.
"""

import json
import uuid
from datetime import datetime
from typing import Optional, List, Dict, Any

from sqlalchemy import (
    create_engine, Column, String, Text, DateTime, Integer, 
    ForeignKey, Boolean, JSON, Float, func
)
from sqlalchemy.orm import declarative_base, sessionmaker, relationship
from sqlalchemy.pool import QueuePool

Base = declarative_base()

# ── ORM Models ──────────────────────────────────────────────────────────

class Project(Base):
    __tablename__ = "projects"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    name = Column(String(255), nullable=False, default="Untitled Project")
    description = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    builds = relationship("Build", back_populates="project", cascade="all, delete-orphan", order_by="Build.created_at")
    chat_messages = relationship("ChatMessage", back_populates="project", cascade="all, delete-orphan", order_by="ChatMessage.created_at")


class Build(Base):
    __tablename__ = "builds"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    project_id = Column(String(36), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    build_id = Column(String(36), nullable=False, comment="UUID used for file naming (exports/cad/{build_id}.stl)")
    prompt = Column(Text, nullable=False)
    code = Column(Text, nullable=True, comment="CadQuery Python code generated by AI")
    parameters = Column(JSON, nullable=True, comment="Parameter definitions [{name, default, min, max, unit}]")
    explanation = Column(JSON, nullable=True, comment="AI explanation {design_intent, features_created, ...}")
    stl_path = Column(String(500), nullable=True)
    step_path = Column(String(500), nullable=True)
    script_path = Column(String(500), nullable=True)
    is_modification = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    project = relationship("Project", back_populates="builds")


class ChatMessage(Base):
    __tablename__ = "chat_messages"

    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    project_id = Column(String(36), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    role = Column(String(20), nullable=False, comment="'user' or 'assistant'")
    content = Column(Text, nullable=False)
    build_result = Column(JSON, nullable=True, comment="Serialized build result for assistant messages")
    status = Column(String(20), nullable=True, comment="success, error, building")
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    project = relationship("Project", back_populates="chat_messages")


# ── Database Service ────────────────────────────────────────────────────

class DatabaseService:
    """MySQL database service using SQLAlchemy sync engine."""

    def __init__(self):
        self.engine = None
        self.Session = None
        self._initialized = False

    def initialize(self, host: str, port: int, user: str, password: str, database: str, pool_size: int = 5):
        """Create engine, session factory, and all tables."""
        connection_url = f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}?charset=utf8mb4"
        
        self.engine = create_engine(
            connection_url,
            pool_size=pool_size,
            max_overflow=10,
            pool_recycle=3600,
            pool_pre_ping=True,
            echo=False,
        )

        # Create tables if they don't exist
        Base.metadata.create_all(self.engine)

        self.Session = sessionmaker(bind=self.engine)
        self._initialized = True
        print("✅ MySQL database initialized successfully")

    @property
    def is_available(self) -> bool:
        return self._initialized

    def _get_session(self):
        if not self._initialized:
            raise RuntimeError("Database not initialized. Call initialize() first.")
        return self.Session()

    # ── Project CRUD ────────────────────────────────────────────────────

    def create_project(self, name: str = "Untitled Project", description: str = None) -> Dict[str, Any]:
        session = self._get_session()
        try:
            project = Project(name=name, description=description)
            session.add(project)
            session.commit()
            result = self._project_to_dict(project)
            return result
        finally:
            session.close()

    def get_project(self, project_id: str) -> Optional[Dict[str, Any]]:
        session = self._get_session()
        try:
            project = session.query(Project).filter_by(id=project_id).first()
            if not project:
                return None
            return self._project_to_dict(project, include_builds=True, include_messages=True)
        finally:
            session.close()

    def list_projects(self) -> List[Dict[str, Any]]:
        session = self._get_session()
        try:
            projects = session.query(Project).order_by(Project.updated_at.desc()).all()
            return [self._project_to_dict(p) for p in projects]
        finally:
            session.close()

    def update_project(self, project_id: str, name: str = None, description: str = None) -> Optional[Dict[str, Any]]:
        session = self._get_session()
        try:
            project = session.query(Project).filter_by(id=project_id).first()
            if not project:
                return None
            if name is not None:
                project.name = name
            if description is not None:
                project.description = description
            project.updated_at = datetime.utcnow()
            session.commit()
            return self._project_to_dict(project)
        finally:
            session.close()

    def delete_project(self, project_id: str) -> bool:
        session = self._get_session()
        try:
            project = session.query(Project).filter_by(id=project_id).first()
            if not project:
                return False
            session.delete(project)
            session.commit()
            return True
        finally:
            session.close()

    # ── Build CRUD ──────────────────────────────────────────────────────

    def save_build(
        self,
        project_id: str,
        build_id: str,
        prompt: str,
        code: str = None,
        parameters: list = None,
        explanation: dict = None,
        stl_path: str = None,
        step_path: str = None,
        script_path: str = None,
        is_modification: bool = False,
    ) -> Dict[str, Any]:
        session = self._get_session()
        try:
            build = Build(
                project_id=project_id,
                build_id=build_id,
                prompt=prompt,
                code=code,
                parameters=parameters,
                explanation=explanation,
                stl_path=stl_path,
                step_path=step_path,
                script_path=script_path,
                is_modification=is_modification,
            )
            session.add(build)

            # Touch parent project updated_at
            project = session.query(Project).filter_by(id=project_id).first()
            if project:
                project.updated_at = datetime.utcnow()

            session.commit()
            return self._build_to_dict(build)
        finally:
            session.close()

    def get_builds_for_project(self, project_id: str) -> List[Dict[str, Any]]:
        session = self._get_session()
        try:
            builds = (
                session.query(Build)
                .filter_by(project_id=project_id)
                .order_by(Build.created_at)
                .all()
            )
            return [self._build_to_dict(b) for b in builds]
        finally:
            session.close()

    def get_all_builds(self, limit: int = 50) -> List[Dict[str, Any]]:
        """Get recent builds across all projects (for history endpoint)."""
        session = self._get_session()
        try:
            builds = (
                session.query(Build)
                .order_by(Build.created_at.desc())
                .limit(limit)
                .all()
            )
            return [self._build_to_dict(b) for b in builds]
        finally:
            session.close()

    # ── Chat Message CRUD ───────────────────────────────────────────────

    def save_chat_message(
        self,
        project_id: str,
        role: str,
        content: str,
        build_result: dict = None,
        status: str = None,
    ) -> Dict[str, Any]:
        session = self._get_session()
        try:
            msg = ChatMessage(
                project_id=project_id,
                role=role,
                content=content,
                build_result=build_result,
                status=status,
            )
            session.add(msg)

            # Touch parent project updated_at
            project = session.query(Project).filter_by(id=project_id).first()
            if project:
                project.updated_at = datetime.utcnow()

            session.commit()
            return self._message_to_dict(msg)
        finally:
            session.close()

    def get_messages_for_project(self, project_id: str) -> List[Dict[str, Any]]:
        session = self._get_session()
        try:
            messages = (
                session.query(ChatMessage)
                .filter_by(project_id=project_id)
                .order_by(ChatMessage.created_at)
                .all()
            )
            return [self._message_to_dict(m) for m in messages]
        finally:
            session.close()

    # ── Serialization helpers ───────────────────────────────────────────

    def _project_to_dict(self, project: Project, include_builds=False, include_messages=False) -> Dict[str, Any]:
        d = {
            "id": project.id,
            "name": project.name,
            "description": project.description,
            "created_at": project.created_at.isoformat() if project.created_at else None,
            "updated_at": project.updated_at.isoformat() if project.updated_at else None,
            "build_count": len(project.builds) if project.builds else 0,
        }
        if include_builds:
            d["builds"] = [self._build_to_dict(b) for b in project.builds]
        if include_messages:
            d["messages"] = [self._message_to_dict(m) for m in project.chat_messages]
        # Grab the latest build's prompt for display
        if project.builds:
            d["last_prompt"] = project.builds[-1].prompt
            d["last_build_id"] = project.builds[-1].build_id
        return d

    def _build_to_dict(self, build: Build) -> Dict[str, Any]:
        return {
            "id": build.id,
            "project_id": build.project_id,
            "build_id": build.build_id,
            "prompt": build.prompt,
            "code": build.code,
            "parameters": build.parameters,
            "explanation": build.explanation,
            "stl_path": build.stl_path,
            "step_path": build.step_path,
            "script_path": build.script_path,
            "is_modification": build.is_modification,
            "created_at": build.created_at.isoformat() if build.created_at else None,
        }

    def _message_to_dict(self, msg: ChatMessage) -> Dict[str, Any]:
        return {
            "id": msg.id,
            "project_id": msg.project_id,
            "role": msg.role,
            "content": msg.content,
            "build_result": msg.build_result,
            "status": msg.status,
            "created_at": msg.created_at.isoformat() if msg.created_at else None,
        }


# ── Module-level singleton ──────────────────────────────────────────────
database_service = DatabaseService()
